### ISSUE TITLE
Add same wallet with mneumonic using azero signer

### ISSUE THREAD

**Issue by Xelendor1** [Zondax/ledger-alephzero#14]
Good afternoon, 

I was curious, could you teach me the derivation path the azero ledger app uses so we can import the same address via azero signer?

**Comment by Xelendor1** [comment]
@carlosala your the best! Thank you~

**Comment by Xelendor1** [comment]
Sorry @carlosala what would be the default path on azero.dev?
![Screenshot 2023-08-03 at 2 17 54 AM](https://github.com/Zondax/ledger-alephzero/assets/20471099/60159cfc-fc91-4685-a3ec-020bb8ead178)

**Comment by carlosala** [comment]
I recommend you enabling expert mode, and then going to show address on hardware device. You should be able to see the app afair!

**Comment by Xelendor1** [comment]
I see this ->. 44'/643'/0'/0'/0' , changed it to /44'/643'/0'/0'/0', but it didn't show the correct address.  am I missing some other apostrophe somewhere?

**Comment by carlosala** [comment]
If you want to get the exact same address, you can see https://github.com/jacogr/substrate-ledger-ed25519 how to get the same key

**Comment by Xelendor1** [comment]
It says it is only compatible with polkadot or kusama.  which one do i use?

**Comment by carlosala** [comment]
You'll need to modify the script to use the derivation path you want, the one I told you before.
I can't provide more support regarding this, I am sorry. This is outside of the scope of a Ledger app.

**Comment by Xelendor1** [comment]
@carlosala if you have free time, and love a challenge, a proper path for the "Azero signer" would be loved <3.  I literally tried every path under the sun for 5 hours or so
