### ISSUE TITLE
Unable to unbond or withdraw rewards from staking via ledger

### ISSUE THREAD

**Issue by dg0313** [Zondax/ledger-alephzero#21]
Hello, 

I'm attempting to withdraw claimable rewards from staking on azero.dev via ledger, but I'm getting the following error message:

nominationPools.claimPayout
Txn version not supported

Also get a similar message when attempting to unbond completely from the nomination poo.

nominationPools.unbond
Txn version not supported

Im currently running version 16.65.1.

Any insight would be greatly appreciated.

Thanks

**Comment by carlosala** [comment]
Hi! Make sure to have latest firmware and app version available in Ledger Live! I see you're running an old version. It should be solved after that!
Have a nice day!
